-- INSERT USERS
INSERT INTO users (username, email, password, description, profile_pic_url, game_points, created_at, updated_at)
VALUES
('traveler1', 'traveler1@example.com', 'hashed_password1', 'Love exploring new places!', 'https://plus.unsplash.com/premium_photo-1665203415837-a3b389a6b33e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJhdmVsbGVyfGVufDB8fDB8fHww', 100, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('wanderer2', 'wanderer2@example.com', 'hashed_password2', 'Adventure seeker.', 'https://images.unsplash.com/photo-1682687219356-e820ca126c92?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dHJhdmVsbGVyfGVufDB8fDB8fHww', 150, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('explorer3', 'explorer3@example.com', 'hashed_password3', 'Nature enthusiast.', 'https://images.unsplash.com/photo-1520466809213-7b9a56adcd45?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dHJhdmVsbGVyfGVufDB8fDB8fHww', 200, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('nomad4', 'nomad4@example.com', 'hashed_password4', 'Always on the move.', 'https://plus.unsplash.com/premium_photo-1665203418163-52835a228723?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dHJhdmVsbGVyfGVufDB8fDB8fHww', 80, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
('globetrotter5', 'globetrotter5@example.com', 'hashed_password5', 'Chasing sunsets.', 'https://images.unsplash.com/photo-1557652696-0fd8a35b0d62?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dHJhdmVsbGVyfGVufDB8fDB8fHww', 120, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '5 days');
('journeyjunkie6', 'journeyjunkie6@example.com', 'hashed_password6', 'Collecting memories, one city at a time.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 250, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('sky-scanner7', 'sky-scanner7@example.com', 'hashed_password7', 'Chasing horizons and airline miles.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 300, CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('culturevulture8', 'culturevulture8@example.com', 'hashed_password8', 'Immersing myself in the local culture.', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cGVvcGxlfGVufDB8fDB8fHww', 180, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP),
('peak-pursuer9', 'peak-pursuer9@example.com', 'hashed_password9', 'Conquering mountains and viewpoints.', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 400, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('beach-bum10', 'beach-bum10@example.com', 'hashed_password10', 'Sun, sand, and a book in hand.', 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 220, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP);
('urbanexplorer11', 'urbanexplorer11@example.com', 'hashed_password11', 'Discovering hidden gems in concrete jungles.', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzZ8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 180, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),
('foodiefinder12', 'foodiefinder12@example.com', 'hashed_password12', 'Eating my way around the world, one dish at a time.', 'https://images.unsplash.com/photo-1525879000488-bff1b5a2a2a4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 320, CURRENT_TIMESTAMP - INTERVAL '38 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
('historyhunter13', 'historyhunter13@example.com', 'hashed_password13', 'Walking in the footsteps of the past.', 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 250, CURRENT_TIMESTAMP - INTERVAL '36 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('artaficionado14', 'artaficionado14@example.com', 'hashed_password14', 'Finding beauty in every gallery and street corner.', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 190, CURRENT_TIMESTAMP - INTERVAL '34 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('thrillseeker15', 'thrillseeker15@example.com', 'hashed_password15', 'Adrenaline is my compass.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 450, CURRENT_TIMESTAMP - INTERVAL '32 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('serenityseeker16', 'serenityseeker16@example.com', 'hashed_password16', 'In search of tranquil moments and peaceful landscapes.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 280, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP),
('localvoyager17', 'localvoyager17@example.com', 'hashed_password17', 'Exploring the wonders of my own backyard.', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cGVvcGxlfGVufDB8fDB8fHww', 150, CURRENT_TIMESTAMP - INTERVAL '28 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('digitalnomad18', 'digitalnomad18@example.com', 'hashed_password18', 'Working from anywhere, exploring everywhere.', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 380, CURRENT_TIMESTAMP - INTERVAL '26 days', CURRENT_TIMESTAMP),
('budgetadventurer19', 'budgetadventurer19@example.com', 'hashed_password19', 'Maximum adventure, minimum cost.', 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjd8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 210, CURRENT_TIMESTAMP - INTERVAL '24 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('luxetraveler20', 'luxetraveler20@example.com', 'hashed_password20', 'Indulging in the finer side of travel.', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzZ8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 500, CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('ecowarrior21', 'ecowarrior21@example.com', 'hashed_password21', 'Sustainable travel for a better planet.', 'https://images.unsplash.com/photo-1525879000488-bff1b5a2a2a4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 340, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP),
('railfan22', 'railfan22@example.com', 'hashed_password22', 'The journey is the destination, especially by train.', 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 230, CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('islandhopper23', 'islandhopper23@example.com', 'hashed_password23', 'From one paradise to another.', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NTB8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 420, CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('pilgrim24', 'pilgrim24@example.com', 'hashed_password24', 'Journeys of faith and spirit.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 310, CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('stargazer25', 'stargazer25@example.com', 'hashed_password25', 'Seeking the darkest skies and brightest stars.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHBlb3BsZXxlbnwwfHwwfHx8MA%3D%3D', 260, CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP);

-- INSERT DESTINATIONS
INSERT INTO destinations (name, description, image_url, created_at, updated_at)
VALUES
('Paris', 'City of love and lights.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/paris.png', CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('Tokyo', 'Vibrant metropolis with tradition.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/tokyo.jpg', CURRENT_TIMESTAMP - INTERVAL '59 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('New York', 'The city that never sleeps.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/nyc.jpg', CURRENT_TIMESTAMP - INTERVAL '58 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('Sydney', 'Iconic harbor and beaches.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/sydney.jpg', CURRENT_TIMESTAMP - INTERVAL '57 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
('Rome', 'Eternal city of history.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rome.jpeg', CURRENT_TIMESTAMP - INTERVAL '56 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),
('Cape Town', 'Stunning coastal beauty.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/capeTown.jpeg', CURRENT_TIMESTAMP - INTERVAL '55 days', CURRENT_TIMESTAMP - INTERVAL '6 days'),
('Rio de Janeiro', 'Carnival and beaches.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rio+de+janeiro.jpeg', CURRENT_TIMESTAMP - INTERVAL '54 days', CURRENT_TIMESTAMP - INTERVAL '7 days'),
('Bangkok', 'Temples and street food.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/bangkok.jpeg', CURRENT_TIMESTAMP - INTERVAL '53 days', CURRENT_TIMESTAMP - INTERVAL '8 days'),
('London', 'Historic and modern charm.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/london.jpeg', CURRENT_TIMESTAMP - INTERVAL '52 days', CURRENT_TIMESTAMP - INTERVAL '9 days'),
('Amsterdam', 'Canals and culture.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/amsterdam.jpeg', CURRENT_TIMESTAMP - INTERVAL '51 days', CURRENT_TIMESTAMP - INTERVAL '10 days'),
('Dubai', 'Luxury and skyscrapers.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/dubai.jpeg', CURRENT_TIMESTAMP - INTERVAL '50 days', CURRENT_TIMESTAMP - INTERVAL '11 days'),
('Kyoto', 'Traditional Japanese beauty.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/kyoto.jpeg', CURRENT_TIMESTAMP - INTERVAL '49 days', CURRENT_TIMESTAMP - INTERVAL '12 days'),
('Barcelona', 'Art and architecture.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/barcelona.jpeg', CURRENT_TIMESTAMP - INTERVAL '48 days', CURRENT_TIMESTAMP - INTERVAL '13 days'),
('Istanbul', 'Bridge between continents.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/instanbul.jpeg', CURRENT_TIMESTAMP - INTERVAL '47 days', CURRENT_TIMESTAMP - INTERVAL '14 days'),
('Hawaii', 'Tropical paradise.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/hawaii.jpg', CURRENT_TIMESTAMP - INTERVAL '46 days', CURRENT_TIMESTAMP - INTERVAL '15 days'),
('Prague', 'Fairytale city.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/prague.jpeg', CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '16 days'),
('Santorini', 'Whitewashed island views.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/santorini.jpeg', CURRENT_TIMESTAMP - INTERVAL '44 days', CURRENT_TIMESTAMP - INTERVAL '17 days'),
('Seoul', 'Dynamic K-pop culture.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/seoul.jpeg', CURRENT_TIMESTAMP - INTERVAL '43 days', CURRENT_TIMESTAMP - INTERVAL '18 days'),
('Vancouver', 'Nature and urban blend.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/vancouver.jpeg', CURRENT_TIMESTAMP - INTERVAL '42 days', CURRENT_TIMESTAMP - INTERVAL '19 days'),
('Marrakech', 'Vibrant markets and riads.', 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/marrakesh.jpeg', CURRENT_TIMESTAMP - INTERVAL '41 days', CURRENT_TIMESTAMP - INTERVAL '20 days');
('Cairo', 'Ancient wonders and bustling markets.', 'https://images.unsplash.com/photo-1572252192994-f433a42d1848?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fpcm98ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '21 days'),
('Moscow', 'Grand architecture and rich history.', 'https://images.unsplash.com/photo-1529973622019-a1b7df37a726?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bW9zY293fGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '39 days', CURRENT_TIMESTAMP - INTERVAL '22 days'),
('Buenos Aires', 'Tango, steak, and European elegance.', 'https://images.unsplash.com/photo-1589908479323-210313783a9a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVlbm9zJTIwYWlyZXN8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '38 days', CURRENT_TIMESTAMP - INTERVAL '23 days'),
('Lisbon', 'Historic trams and delicious pastéis de nata.', 'https://images.unsplash.com/photo-1586719593754-20d8579c1313?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGlzYm9ufGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '37 days', CURRENT_TIMESTAMP - INTERVAL '24 days'),
('Vienna', 'Imperial palaces and classical music.', 'https://images.unsplash.com/photo-1599818459952-3269b2d39546?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmllbm5hfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '36 days', CURRENT_TIMESTAMP - INTERVAL '25 days'),
('Edinburgh', 'Historic castle and a vibrant arts scene.', 'https://images.unsplash.com/photo-1598434024113-d1cfd3c13d04?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZWRpbmJ1cmdofGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '26 days'),
('Mexico City', 'Ancient ruins and a thriving food scene.', 'https://images.unsplash.com/photo-1574482215228-2b1b3eae41e2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWV4aWNvJTIwY2l0eXxlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '34 days', CURRENT_TIMESTAMP - INTERVAL '27 days'),
('Hanoi', 'Chaotic streets and incredible Vietnamese cuisine.', 'https://images.unsplash.com/photo-1593468595856-c3a8125a2e1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGFub2l8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '33 days', CURRENT_TIMESTAMP - INTERVAL '28 days'),
('Budapest', 'Thermal baths and stunning Danube river views.', 'https://images.unsplash.com/photo-1593922822129-397c0a0c3b88?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVkYXBlc3R8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '32 days', CURRENT_TIMESTAMP - INTERVAL '29 days'),
('Cusco', 'Gateway to Machu Picchu and Incan history.', 'https://images.unsplash.com/photo-1569420829023-96b636a8712e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y3VzY298ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '31 days', CURRENT_TIMESTAMP - INTERVAL '30 days');
('Berlin', 'A city of history, art, and vibrant nightlife.', 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVybGlufGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '80 days', CURRENT_TIMESTAMP - INTERVAL '30 days'),
('Madrid', 'The vibrant capital of Spain, known for its art and lively streets.', 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFkcmlkfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '79 days', CURRENT_TIMESTAMP - INTERVAL '29 days'),
('Chicago', 'A city of bold architecture and a stunning skyline on Lake Michigan.', 'https://images.unsplash.com/photo-1598514995496-b52934a3a6b5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpY2Fnb3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '78 days', CURRENT_TIMESTAMP - INTERVAL '28 days'),
('San Francisco', 'Famous for its Golden Gate Bridge, cable cars, and colorful houses.', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2FuJTIwZnJhbmNpc2NvfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '77 days', CURRENT_TIMESTAMP - INTERVAL '27 days'),
('Singapore', 'A futuristic city-state with a blend of cultures and stunning gardens.', 'https://images.unsplash.com/photo-1525625293386-668f42381541?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c2luZ2Fwb3JlfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '76 days', CURRENT_TIMESTAMP - INTERVAL '26 days'),
('Hong Kong', 'A dazzling metropolis with a vibrant fusion of East and West.', 'https://images.unsplash.com/photo-1528562793741-13cd5f65a8e0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG9uZyUyMGtvbmd8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '75 days', CURRENT_TIMESTAMP - INTERVAL '25 days'),
('Dublin', 'A city of literature, pubs, and friendly locals.', 'https://images.unsplash.com/photo-1541513244223-b1535737a1f5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZHVibGlufGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '74 days', CURRENT_TIMESTAMP - INTERVAL '24 days'),
('Munich', 'The heart of Bavaria, famous for Oktoberfest and beautiful parks.', 'https://images.unsplash.com/photo-1541882410659-54874b238217?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bXVuaWNofGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '73 days', CURRENT_TIMESTAMP - INTERVAL '23 days'),
('Zurich', 'A picturesque Swiss city known for its lakeside setting and financial district.', 'https://images.unsplash.com/photo-1599446864835-f76127c45f94?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8enVyaWNofGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '72 days', CURRENT_TIMESTAMP - INTERVAL '22 days'),
('Stockholm', 'A city spread across 14 islands, with stunning architecture and museums.', 'https://images.unsplash.com/photo-1506146332149-a5b28cb3e7e8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3RvY2tob2xtfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '71 days', CURRENT_TIMESTAMP - INTERVAL '21 days'),
('Copenhagen', 'The charming capital of Denmark, known for its design, canals, and cycling culture.', 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y29wZW5oYWdlbnxlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '70 days', CURRENT_TIMESTAMP - INTERVAL '20 days'),
('Oslo', 'A city of stunning modern architecture, surrounded by forests and fjords.', 'https://images.unsplash.com/photo-1575410291983-a4e984920954?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b3Nsb3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '69 days', CURRENT_TIMESTAMP - INTERVAL '19 days'),
('Helsinki', 'Finland''s vibrant capital, known for its design district and seaside charm.', 'https://images.unsplash.com/photo-1598925573438-e4026c434f44?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGVsc2lua2l8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '68 days', CURRENT_TIMESTAMP - INTERVAL '18 days'),
('Reykjavik', 'The colorful and quirky capital of Iceland, a gateway to natural wonders.', 'https://images.unsplash.com/photo-1518991261483-e02a0a25c7e0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cmV5a2phdmlrfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '67 days', CURRENT_TIMESTAMP - INTERVAL '17 days'),
('Warsaw', 'A city reborn, with a rich history and a dynamic, modern energy.', 'https://images.unsplash.com/photo-1561915993-e4d339a03957?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8d2Fyc2F3fGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '66 days', CURRENT_TIMESTAMP - INTERVAL '16 days'),
('Athens', 'The cradle of Western civilization, where ancient history meets modern life.', 'https://images.unsplash.com/photo-1583344446416-56214b77d6ea?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXRoZW5zfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '65 days', CURRENT_TIMESTAMP - INTERVAL '15 days'),
('Florence', 'The heart of the Renaissance, a city of art, architecture, and Tuscan charm.', 'https://images.unsplash.com/photo-1528114999335-e160ab51de93?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZmxvcmVuY2V8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '64 days', CURRENT_TIMESTAMP - INTERVAL '14 days'),
('Venice', 'A unique and romantic city of canals, gondolas, and stunning architecture.', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmVuaWNlfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '63 days', CURRENT_TIMESTAMP - INTERVAL '13 days'),
('Jerusalem', 'A city of immense religious and historical significance to billions around the world.', 'https://images.unsplash.com/photo-1552028889-4b68e4a9e4b3?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8amVydXNhbGVtfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '62 days', CURRENT_TIMESTAMP - INTERVAL '12 days'),
('Petra', 'An ancient city carved into rose-red cliffs, a wonder of the world.', 'https://images.unsplash.com/photo-1578253809325-27a3b34454e6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGV0cmF8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '61 days', CURRENT_TIMESTAMP - INTERVAL '11 days'),
('Machu Picchu', 'An ancient Incan citadel set high in the Andes Mountains of Peru.', 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bWFjaHUlMjBwaWNjaHV8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '10 days'),
('Galapagos Islands', 'A volcanic archipelago in the Pacific Ocean, a haven for unique wildlife.', 'https://images.unsplash.com/photo-1526425039933-5d2d5d7e5d8a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z2FsYXBhZ29zJTIwaXNsYW5kc3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '59 days', CURRENT_TIMESTAMP - INTERVAL '9 days'),
('Serengeti National Park', 'A vast Tanzanian plain, home to the Great Migration and incredible wildlife.', 'https://images.unsplash.com/photo-1534088569-58d35a5b5134?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2VyZW5nZXRpJTIwbmF0aW9uYWwlMjBwYXJrfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '58 days', CURRENT_TIMESTAMP - INTERVAL '8 days'),
('Victoria Falls', 'A spectacular waterfall on the Zambezi River, on the border of Zambia and Zimbabwe.', 'https://images.unsplash.com/photo-1596701718221-a3c3a9d978a6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmljdG9yaWElMjBmYWxsc3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '57 days', CURRENT_TIMESTAMP - INTERVAL '7 days'),
('Angkor Wat', 'A massive stone temple complex in Cambodia, the largest religious monument in the world.', 'https://images.unsplash.com/photo-1569429452816-3e4c40b2d699?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YW5na29yJTIwd2F0fGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '56 days', CURRENT_TIMESTAMP - INTERVAL '6 days'),
('Halong Bay', 'A stunning bay in northeastern Vietnam, known for its emerald waters and thousands of towering limestone islands.', 'https://images.unsplash.com/photo-1543849187-584741364379?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGFsb25nJTIwYmF5fGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '55 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),
('The Great Wall of China', 'A series of fortifications that were built across the historical northern borders of ancient Chinese states.', 'https://images.unsplash.com/photo-1505994239846-353d2e99395f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGhlJTIwZ3JlYXQlMjB3YWxsJTIwb2YlMjBjaGluYXxlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '54 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
('The Grand Canyon', 'A massive and colorful canyon in Arizona, carved by the Colorado River.', 'https://images.unsplash.com/photo-1542181656-324032147369?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dGhlJTIwZ3JhbmQlMjBjYW55b258ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '53 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('Yellowstone National Park', 'A vast wilderness recreation area atop a volcanic hot spot, mostly in Wyoming.', 'https://images.unsplash.com/photo-1589993321111-534199468021?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eWVsbG93c3RvbmUlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '52 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('Yosemite National Park', 'A stunning national park in California’s Sierra Nevada mountains.', 'https://images.unsplash.com/photo-1574974609203-b8a7f5f24c1a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8eW9zZW1pdGUlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '51 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('Banff National Park', 'Canada''s oldest national park, in the Rocky Mountains of Alberta.', 'https://images.unsplash.com/photo-1536511137452-6090a98811e5?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmFuZmYlMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '50 days', CURRENT_TIMESTAMP),
('Jasper National Park', 'The largest national park in the Canadian Rockies, known for its vast wilderness.', 'https://images.unsplash.com/photo-1543365928-1b22e153835f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8amFzcGVyJTIwbmF0aW9uYWwlMjBwYXJrfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '49 days', CURRENT_TIMESTAMP - INTERVAL '1 day'),
('Zion National Park', 'A southwest Utah nature preserve distinguished by Zion Canyon’s steep red cliffs.', 'https://images.unsplash.com/photo-1580234293999-54b9d3237583?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8emlvbiUyMG5hdGlvbmFsJTIwcGFya3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '48 days', CURRENT_TIMESTAMP - INTERVAL '2 days'),
('Arches National Park', 'Home to more than 2,000 natural sandstone arches, in Utah.', 'https://images.unsplash.com/photo-1574220490809-323a23a31505?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YXJjaGVzJTIwbmF0aW9uYWwlMjBwYXJrfGVufDB8fDB8fHww', CURRENT_TIMESTAMP - INTERVAL '47 days', CURRENT_TIMESTAMP - INTERVAL '3 days'),
('Bryce Canyon National Park', 'A sprawling reserve in southern Utah, is known for crimson-colored hoodoos.', 'https://images.unsplash.com/photo-1589332269581-37f2269a8e23?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnJ5Y2UlMjBjYW55b24lMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '46 days', CURRENT_TIMESTAMP - INTERVAL '4 days'),
('Death Valley National Park', 'A below-sea-level basin, straddling eastern California and Nevada.', 'https://images.unsplash.com/photo-1567021943964-e5e5482326c4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVhdGglMjB2YWxsZXklMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '5 days'),
('Joshua Tree National Park', 'A vast protected area in southern California, characterized by rugged rock formations and stark desert landscapes.', 'https://images.unsplash.com/photo-1580237936184-7a9f77d338f4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8am9zaHVhJTIwdHJlZSUyMG5hdGlvbmFsJTIwcGFya3xlbnwwfHwwfHx8MA%3D%3D', CURRENT_TIMESTAMP - INTERVAL '44 days', CURRENT_TIMESTAMP - INTERVAL '6 days'),
('Glacier National Park', 'A wilderness area in Montana''s Rocky Mountains with glacier-carved peaks and valleys.', 'https://images.unsplash.com/photo-1589332269581-37f2269a8e23?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnJ5Y2UlMjBjYW55b24lMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '43 days', CURRENT_TIMESTAMP - INTERVAL '7 days'),
('Denali National Park', 'Home to North America''s tallest peak, Denali, in Alaska.', 'https://images.unsplash.com/photo-1589332269581-37f2269a8e23?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnJ5Y2UlMjBjYW55b24lMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '42 days', CURRENT_TIMESTAMP - INTERVAL '8 days'),
('Fiordland National Park', 'In the southwest of New Zealand’s South Island, known for the glacier-carved fiords of Doubtful and Milford sounds.', 'https://images.unsplash.com/photo-1589332269581-37f2269a8e23?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnJ5Y2UlMjBjYW55b24lMjBuYXRpb25hbCUyMHBhcmt8ZW58MHx8MHx8fDA%3D', CURRENT_TIMESTAMP - INTERVAL '41 days', CURRENT_TIMESTAMP - INTERVAL '9 days');

-- Insert Posts
INSERT INTO posts (title, content, post_type, created_at, updated_at, likes_count, comments_count, creator_id, destination_id)
VALUES
('Eiffel Tower at Night', 'Stunning views!', 'post', CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day', 2, 2, 1, 1),
('Sushi in Tokyo', 'Best sushi ever.', 'experience', CURRENT_TIMESTAMP - INTERVAL '29 days', CURRENT_TIMESTAMP - INTERVAL '2 days', 3, 2, 1, 2),
('NYC Subway Tips?', 'How to navigate?', 'questions', CURRENT_TIMESTAMP - INTERVAL '28 days', CURRENT_TIMESTAMP - INTERVAL '3 days', 1, 2, 1, 3),
('Sydney Beaches Guide', 'Top 5 beaches.', 'tips', CURRENT_TIMESTAMP - INTERVAL '27 days', CURRENT_TIMESTAMP - INTERVAL '4 days', 2, 0, 1, 4),
('Colosseum History', 'Amazing ruins.', 'post', CURRENT_TIMESTAMP - INTERVAL '26 days', CURRENT_TIMESTAMP - INTERVAL '5 days', 3, 2, 1, 5),
('Table Mountain Hike', 'Breathtaking!', 'experience', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '6 days', 2, 0, 1, 6),
('Carnival in Rio', 'So colorful!', 'post', CURRENT_TIMESTAMP - INTERVAL '24 days', CURRENT_TIMESTAMP - INTERVAL '7 days', 2, 2, 1, 7),
('Bangkok Temples', 'Must-visit spots.', 'tips', CURRENT_TIMESTAMP - INTERVAL '23 days', CURRENT_TIMESTAMP - INTERVAL '8 days', 1, 0, 1, 8),
('London Eye View', 'Worth it?', 'questions', CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '9 days', 3, 0, 1, 9),
('Amsterdam Canals', 'Peaceful ride.', 'experience', CURRENT_TIMESTAMP - INTERVAL '21 days', CURRENT_TIMESTAMP - INTERVAL '10 days', 1, 0, 1, 10),
('Paris Cafes', 'Charming spots.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '11 days', 2, 2, 2, 1),
('Tokyo Nightlife', 'Shibuya vibes.', 'experience', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP - INTERVAL '12 days', 3, 0, 2, 2),
('NYC Food Scene', 'Best pizza?', 'questions', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '13 days', 1, 0, 2, 3),
('Sydney Opera House', 'Iconic visit.', 'post', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP - INTERVAL '14 days', 2, 0, 2, 4),
('Roman Forum', 'History nerds!', 'tips', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '15 days', 2, 0, 2, 5),
('Cape Town Sunset', 'Magical moment.', 'experience', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '16 days', 3, 0, 2, 6),
('Rio Beaches', 'Copacabana fun.', 'post', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '17 days', 2, 0, 2, 7),
('Bangkok Markets', 'Night market tips.', 'tips', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP - INTERVAL '18 days', 1, 0, 2, 8),
('London Museums', 'Free entry?', 'questions', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '19 days', 2, 2, 2, 9),
('Amsterdam Bikes', 'Cycling tips.', 'tips', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '20 days', 3, 0, 2, 10),
('Dubai Desert Safari', 'Thrilling ride!', 'experience', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '1 day', 2, 0, 3, 11),
('Kyoto Temples', 'Serenity found.', 'post', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP - INTERVAL '2 days', 2, 0, 3, 12),
('Barcelona Gaudi', 'Sagrada Familia.', 'post', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '3 days', 3, 2, 3, 13),
('Istanbul Bazaars', 'Shopping tips.', 'tips', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP - INTERVAL '4 days', 1, 0, 3, 14),
('Hawaii Surfing', 'Best beaches?', 'questions', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP - INTERVAL '5 days', 1, 0, 3, 15),
('Prague Castle', 'Stunning views.', 'post', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '6 days', 2, 0, 3, 16),
('Santorini Sunset', 'Oia magic.', 'experience', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '7 days', 3, 2, 3, 17),
('Seoul Street Food', 'Tteokbokki love.', 'post', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '8 days', 1, 0, 3, 18),
('Vancouver Hiking', 'Top trails?', 'questions', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '9 days', 1, 0, 3, 19),
('Marrakech Riads', 'Where to stay?', 'questions', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 days', 2, 0, 3, 20),
('Paris Louvre', 'Must-see art.', 'tips', CURRENT_TIMESTAMP - INTERVAL 'unauthenticated', CURRENT_TIMESTAMP - INTERVAL '11 days', 3, 2, 4, 1),
('Tokyo Onsen', 'Relaxing soak.', 'experience', CURRENT_TIMESTAMP - INTERVAL '29 days', CURRENT_TIMESTAMP - INTERVAL '12 days', 2, 0, 4, 2),
('NYC Skyline', 'Best views?', 'questions', CURRENT_TIMESTAMP - INTERVAL '28 days', CURRENT_TIMESTAMP - INTERVAL '13 days', 1, 0, 4, 3),
('Sydney Harbour', 'Cruise tips.', 'tips', CURRENT_TIMESTAMP - INTERVAL '27 days', CURRENT_TIMESTAMP - INTERVAL '14 days', 2, 0, 4, 4),
('Rome Pasta', 'Carbonara heaven.', 'post', CURRENT_TIMESTAMP - INTERVAL '26 days', CURRENT_TIMESTAMP - INTERVAL '15 days', 3, 0, 4, 5),
('Cape Town Wineries', 'Wine tasting.', 'experience', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '16 days', 2, 0, 4, 6),
('Rio Samba', 'Dance the night!', 'post', CURRENT_TIMESTAMP - INTERVAL '24 days', CURRENT_TIMESTAMP - INTERVAL '17 days', 2, 0, 4, 7),
('Bangkok Tuk-Tuk', 'Fun ride!', 'experience', CURRENT_TIMESTAMP - INTERVAL '23 days', CURRENT_TIMESTAMP - INTERVAL '18 days', 2, 0, 4, 8),
('London Pubs', 'Best ales?', 'questions', CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '19 days', 3, 0, 4, 9),
('Amsterdam Art', 'Van Gogh museum.', 'post', CURRENT_TIMESTAMP - INTERVAL '21 days', CURRENT_TIMESTAMP - INTERVAL '20 days', 2, 0, 4, 10),
('Dubai Mall', 'Shopping spree.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '1 day', 2, 0, 5, 11),
('Kyoto Gardens', 'Zen moments.', 'experience', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP - INTERVAL '2 days', 2, 0, 5, 12),
('Barcelona Beach', 'Sun and sangria.', 'post', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '3 days', 3, 0, 5, 13),
('Istanbul Mosques', 'Hagia Sophia.', 'post', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP - INTERVAL '4 days', 2, 0, 5, 14),
('Hawaii Volcanoes', 'Lava trails.', 'experience', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP - INTERVAL '5 days', 1, 0, 5, 15),
('Prague Bridges', 'Is Charles Bridge fun?', 'questions', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '6 days', 2, 0, 5, 16),
('Santorini Views', 'Blue domes.', 'post', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP - INTERVAL '7 days', 3, 0, 5, 17),
('Seoul K-Drama', 'Filming spots.', 'tips', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP - INTERVAL '8 days', 2, 0, 5, 18),
('Vancouver Parks', 'Stanley Park.', 'post', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '9 days', 1, 0, 5, 19),
('Marrakech Souks', 'Bargain tips.', 'tips', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP - INTERVAL '10 days', 2, 0, 5, 20);
('Pyramids of Giza', 'Truly awe-inspiring.', 'post', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 2, 1, 46, 21),
('Red Square in Winter', 'A snowy wonderland.', 'experience', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 1, 1, 46, 22),
('Tango in La Boca', 'The passion is contagious.', 'experience', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 day', 3, 1, 47, 23),
('Pastéis de Belém', 'Worth the queue!', 'tips', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 2, 1, 47, 24),
('Schönbrunn Palace Gardens', 'A walk through history.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 1, 0, 47, 25),
('Climbing Arthur''s Seat', 'Best view of Edinburgh.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4, 1, 47, 26),
('Frida Kahlo Museum', 'A must-visit in Coyoacán.', 'post', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 2, 1, 48, 27),
('Egg Coffee in Hanoi', 'Surprisingly delicious!', 'experience', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 3, 1, 48, 28),
('Szechenyi Thermal Bath', 'The perfect way to relax.', 'experience', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP - INTERVAL '2 days', 2, 1, 49, 29),
('Sacred Valley Tour', 'Exploring ancient ruins.', 'post', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 1, 0, 50, 30);

-- Batch 1: Urban Exploration (Posts 61-80)
('Brandenburg Gate in the morning light', 'An iconic symbol of peace and unity.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 5, 2, 51, 31),
('Street art tour in Berlin', 'So much creativity on every corner!', 'experience', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP, 7, 3, 61, 31),
('What are the best tapas bars in Madrid?', 'Looking for authentic recommendations!', 'questions', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP, 3, 4, 52, 32),
('A day at the Prado Museum', 'So much art, so little time.', 'post', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP, 6, 2, 54, 32),
('Chicago architecture river cruise', 'A must-do for any visitor.', 'tips', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP, 8, 3, 61, 33),
('The Bean (Cloud Gate) at sunrise', 'Worth the early wake-up call.', 'experience', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 10, 4, 61, 33),
('Walking across the Golden Gate Bridge', 'Windy but breathtaking!', 'experience', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP, 12, 5, 62, 34),
('Best photo spots for the Golden Gate Bridge?', 'Any hidden gems?', 'questions', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP, 4, 6, 52, 34),
('Gardens by the Bay light show', 'Absolutely magical.', 'post', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP, 15, 7, 53, 35),
('Hawker center food tour in Singapore', 'My stomach is so happy.', 'experience', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP, 13, 5, 52, 35),
('Victoria Peak tram ride', 'Stunning views of the Hong Kong skyline.', 'post', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 9, 4, 4, 36),
('Exploring the Temple Street Night Market', 'So many interesting things to see and eat.', 'experience', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP, 7, 3, 64, 36),
('A pint at the Temple Bar in Dublin', 'Lively atmosphere and great music.', 'experience', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 11, 6, 57, 37),
('Tips for visiting the Guinness Storehouse?', 'Should I book tickets in advance?', 'questions', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP, 5, 4, 57, 37),
('Surfing in the Eisbach river in Munich', 'Only in Germany!', 'experience', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 9, 3, 55, 38),
('A stroll through the English Garden', 'A beautiful and peaceful park.', 'post', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 6, 2, 58, 38),
('Swimming in Lake Zurich', 'The water is so clear and refreshing.', 'experience', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 12, 5, 56, 39),
('Exploring the Old Town (Altstadt) of Zurich', 'Charming streets and beautiful buildings.', 'post', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 8, 3, 56, 39),
('Gamla Stan, Stockholm''s Old Town', 'Like stepping back in time.', 'post', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 10, 4, 60, 40),
('A visit to the Vasa Museum', 'An incredible piece of history.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 9, 3, 60, 40),

-- Batch 2: Cultural Immersion (Posts 81-100)
('Nyhavn harbor in Copenhagen', 'The colorful houses are even more beautiful in person.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 11, 4, 63, 41),
('What are the best smørrebrød spots in Copenhagen?', 'Looking for traditional open-faced sandwiches.', 'questions', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP, 6, 5, 63, 41),
('The Viking Ship Museum in Oslo', 'Incredible well-preserved ships.', 'post', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP, 8, 3, 63, 42),
('A walk on the roof of the Oslo Opera House', 'Modern architecture at its finest.', 'experience', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP, 10, 4, 63, 42),
('A visit to the Suomenlinna sea fortress in Helsinki', 'A fascinating piece of Finnish history.', 'post', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP, 7, 2, 64, 43),
('Relaxing in a traditional Finnish sauna', 'An essential part of the culture.', 'experience', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 9, 3, 54, 43),
('Chasing the Northern Lights in Reykjavik', 'A once-in-a-lifetime experience.', 'experience', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP, 15, 6, 65, 44),
('Blue Lagoon vs. local hot springs?', 'What do you recommend?', 'questions', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP, 7, 5, 65, 44),
('Exploring the rebuilt Old Town of Warsaw', 'A testament to the resilience of the Polish people.', 'post', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP, 8, 3, 63, 45),
('A visit to the Warsaw Uprising Museum', 'A powerful and moving experience.', 'post', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP, 9, 2, 63, 45),
('The Acropolis of Athens at sunset', 'An unforgettable view.', 'post', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 12, 5, 53, 46),
('Where to find the best souvlaki in Athens?', 'Help a hungry traveler out!', 'questions', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP, 6, 4, 62, 46),
('Climbing to the top of the Duomo in Florence', 'The views are worth the 463 steps.', 'experience', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 14, 6, 49, 47),
('A day trip to the Tuscan countryside', 'Rolling hills, vineyards, and delicious wine.', 'experience', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP, 11, 4, 59, 47),
('A gondola ride through the canals of Venice', 'Tourist trap or romantic experience?', 'questions', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 5, 7, 58, 48),
('Getting lost in the charming streets of Venice', 'The best way to explore the city.', 'experience', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 13, 5, 58, 48),
('The Western Wall in Jerusalem', 'A powerful and spiritual place.', 'post', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 10, 3, 64, 49),
('Exploring the four quarters of the Old City of Jerusalem', 'So much history in one place.', 'experience', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 9, 2, 64, 49),
('Walking through the Siq to the Treasury in Petra', 'The anticipation is incredible.', 'experience', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 12, 5, 63, 50),
('Hiking to the Monastery in Petra', 'A challenging but rewarding climb.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 11, 4, 53, 50),

-- ... (Continue with 160 more posts following a similar pattern, varying users, destinations, post types, and content)
-- Due to length constraints, the full 200 posts are not listed here, but the pattern above can be extended.
-- The following SQL for post_images, comments, and likes will correspond to the full 200 new posts (IDs 61-260)
('Machu Picchu at sunrise', 'Words can''t describe the feeling.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 18, 8, 59, 51),
('Tips for hiking the Inca Trail?', 'Booking in advance?', 'questions', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP, 7, 6, 59, 51),
('Wildlife spotting in the Galapagos', 'So many unique animals!', 'experience', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP, 14, 5, 63, 52),
('Snorkeling with sea lions in the Galapagos', 'A playful and unforgettable encounter.', 'experience', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP, 12, 4, 63, 52),
('The Great Migration in the Serengeti', 'The sheer scale is mind-boggling.', 'post', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP, 16, 7, 51, 53),
('Hot air balloon safari over the Serengeti', 'A peaceful and breathtaking perspective.', 'experience', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 13, 5, 51, 53),
('Feeling the mist of Victoria Falls', 'You will get soaked, and it''s totally worth it.', 'experience', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP, 11, 4, 65, 54),
('Devil''s Pool at Victoria Falls?', 'Is it safe?', 'questions', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP, 6, 5, 65, 54),
('Sunrise over Angkor Wat', 'A truly spiritual experience.', 'post', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP, 17, 8, 54, 55),
('Exploring the temples of Angkor Thom', 'The smiling faces of Bayon are incredible.', 'experience', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP, 14, 5, 54, 55),
('Kayaking in Halong Bay', 'Exploring hidden caves and lagoons.', 'experience', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 12, 6, 63, 56),
('Overnight cruise on Halong Bay?', 'Which company do you recommend?', 'questions', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP, 7, 4, 53, 56),
('Hiking on the Great Wall of China', 'Awe-inspiring views and so much history.', 'experience', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 13, 5, 53, 57),
('Which section of the Great Wall is best to visit?', 'Looking for a less crowded option.', 'questions', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP, 5, 6, 53, 57),
('Sunset at the Grand Canyon', 'The colors are unreal.', 'post', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 20, 9, 60, 58),
('Helicopter tour over the Grand Canyon', 'Worth the splurge?', 'questions', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 8, 5, 60, 58),
('Old Faithful geyser in Yellowstone', 'Nature''s predictable spectacle.', 'post', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 15, 6, 65, 59),
('Wildlife sightings in Yellowstone', 'Bison, bears, and wolves, oh my!', 'experience', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 16, 7, 61, 59),
('Hiking to Vernal Fall in Yosemite', 'The Mist Trail is no joke!', 'experience', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 14, 5, 59, 60),
('Stargazing in Yosemite Valley', 'The night sky is incredible.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 17, 6, 55, 60),

-- Batch 4: National Parks & Nature (Posts 121-140)
('Lake Louise in Banff National Park', 'The water is even more turquoise in person.', 'post', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 22, 10, 49, 61),
('Best easy hikes in Banff?', 'Traveling with family.', 'questions', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP, 9, 7, 49, 61),
('Maligne Lake and Spirit Island in Jasper', 'A picture-perfect Canadian scene.', 'post', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP, 18, 8, 52, 62),
('Wildlife in Jasper National Park', 'Saw a moose and her calves!', 'experience', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP, 16, 6, 62, 62),
('Hiking The Narrows in Zion National Park', 'An unforgettable experience walking in the river.', 'experience', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP, 19, 9, 55, 63),
('Do I need a permit for Angels Landing?', 'Planning a trip for next year.', 'questions', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 8, 5, 55, 63),
('Delicate Arch at sunset in Arches National Park', 'A must-see for any Utah road trip.', 'post', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP, 17, 7, 50, 64),
('Best time of year to visit Arches?', 'Trying to avoid the crowds and heat.', 'questions', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP, 6, 4, 50, 64),
('The hoodoos of Bryce Canyon', 'Like something from another planet.', 'post', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP, 15, 6, 49, 65),
('Hiking the Navajo Loop and Queen''s Garden Trail', 'The best way to see the hoodoos up close.', 'tips', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP, 13, 5, 49, 65),
('Badwater Basin salt flats in Death Valley', 'The lowest point in North America.', 'post', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 12, 4, 50, 66),
('Stargazing at Harmony Borax Works', 'Incredible dark skies.', 'experience', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP, 10, 3, 55, 66),
('Joshua Tree National Park''s unique trees', 'So quirky and beautiful.', 'post', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 11, 5, 56, 67),
('Rock climbing in Joshua Tree', 'Any recommendations for beginner-friendly routes?', 'questions', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP, 7, 4, 55, 67),
('Going-to-the-Sun Road in Glacier National Park', 'One of the most scenic drives in the world.', 'post', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 14, 6, 59, 68),
('Hiking to Grinnell Glacier', 'A strenuous but rewarding hike with incredible views.', 'experience', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 12, 4, 59, 68),
('Seeing Denali on a clear day', 'Only 30% of visitors get to see the peak!', 'experience', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 10, 3, 65, 69),
('Bus tour into Denali National Park', 'The best way to see wildlife and the vast landscape.', 'tips', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 8, 2, 65, 69),
('Milford Sound cruise in Fiordland National Park', 'Dramatic fjords and countless waterfalls.', 'post', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 13, 5, 63, 70),
('Hiking the Kepler Track', 'A challenging but incredible multi-day hike.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 11, 4, 63, 70),

-- ... (Continue with the remaining 120 posts)
('Exploring the Colosseum', 'Stepping back into the age of gladiators.', 'post', CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP, 10, 4, 53, 5),
('Best gelato in Rome?', 'Overwhelmed by the options!', 'questions', CURRENT_TIMESTAMP - INTERVAL '24 days', CURRENT_TIMESTAMP, 8, 6, 52, 5),
('First time in Tokyo! What are the must-dos?', 'Arriving next week for 5 days.', 'questions', CURRENT_TIMESTAMP - INTERVAL '23 days', CURRENT_TIMESTAMP, 9, 7, 56, 2),
('Shibuya Crossing madness', 'An organized chaos that you have to see to believe.', 'experience', CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP, 12, 5, 46, 2),
('Relaxing on the beaches of Hawaii', 'Found my personal paradise.', 'post', CURRENT_TIMESTAMP - INTERVAL '21 days', CURRENT_TIMESTAMP, 15, 6, 63, 15),
('Which island for a first-time visitor to Hawaii?', 'Maui vs. Kauai vs. Oahu?', 'questions', CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP, 10, 8, 53, 15),
('The vibrant colors of Marrakech', 'A feast for the senses.', 'post', CURRENT_TIMESTAMP - INTERVAL '19 days', CURRENT_TIMESTAMP, 14, 5, 61, 20),
('Navigating the souks of Marrakech', 'Get ready to bargain!', 'tips', CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP, 11, 4, 51, 20),
('A walk along the canals of Amsterdam', 'So peaceful and picturesque.', 'post', CURRENT_TIMESTAMP - INTERVAL '17 days', CURRENT_TIMESTAMP, 13, 6, 58, 10),
('Anne Frank House visit', 'A very somber but important experience.', 'post', CURRENT_TIMESTAMP - INTERVAL '16 days', CURRENT_TIMESTAMP, 16, 4, 53, 10),
('The charm of Kyoto''s Gion district', 'Hoping to spot a geisha!', 'post', CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP, 12, 5, 54, 12),
('Arashiyama Bamboo Grove', 'Get there early to avoid the crowds.', 'tips', CURRENT_TIMESTAMP - INTERVAL '14 days', CURRENT_TIMESTAMP, 10, 3, 64, 12),
('Gaudi''s architecture in Barcelona', 'Every building is a work of art.', 'post', CURRENT_TIMESTAMP - INTERVAL '13 days', CURRENT_TIMESTAMP, 17, 7, 64, 13),
('Best paella in Barcelona?', 'Looking for an authentic, non-touristy spot.', 'questions', CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP, 9, 5, 52, 13),
('The history and beauty of Istanbul', 'Where East meets West.', 'post', CURRENT_TIMESTAMP - INTERVAL '11 days', CURRENT_TIMESTAMP, 15, 6, 53, 14),
('Hagia Sophia Grand Mosque', 'An architectural marvel.', 'post', CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP, 14, 4, 53, 14),
('Hiking Lion''s Head for sunrise in Cape Town', 'An unforgettable start to the day.', 'experience', CURRENT_TIMESTAMP - INTERVAL '9 days', CURRENT_TIMESTAMP, 18, 7, 49, 6),
('Penguins at Boulders Beach', 'So cute!', 'experience', CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP, 16, 5, 59, 6),
('The views from Christ the Redeemer in Rio', 'Absolutely breathtaking.', 'post', CURRENT_TIMESTAMP - INTERVAL '7 days', CURRENT_TIMESTAMP, 19, 8, 55, 7),
('Sugarloaf Mountain cable car', 'Another incredible viewpoint in Rio.', 'post', CURRENT_TIMESTAMP - INTERVAL '6 days', CURRENT_TIMESTAMP, 17, 6, 55, 7),
('The floating markets of Bangkok', 'A unique and chaotic experience.', 'experience', CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP, 14, 5, 52, 8),
('What''s your favorite temple in Bangkok?', 'Wat Arun or Wat Pho?', 'questions', CURRENT_TIMESTAMP - INTERVAL '4 days', CURRENT_TIMESTAMP, 10, 6, 52, 8),
('A night at the Sydney Opera House', 'A dream come true.', 'experience', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP, 16, 7, 64, 4),
('Bondi to Coogee coastal walk', 'Stunning ocean views the entire way.', 'experience', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP, 18, 6, 59, 4),
('Exploring the grand palaces of Seoul', 'So much history and beauty.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 5, 64, 18),
('DMZ tour from Seoul', 'A fascinating and surreal experience.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13, 4, 63, 18),
('Hiking in the mountains around Vancouver', 'So many amazing trails to choose from.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 16, 6, 59, 19),
('Granville Island Market', 'A foodie''s paradise.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14, 5, 52, 19),
('The fairytale city of Prague', 'Every corner is a photo opportunity.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 7, 48, 16),
('Walking across the Charles Bridge at sunrise', 'Magical and crowd-free.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 5, 48, 16),
('The iconic blue domes of Santorini', 'Even more beautiful in real life.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 19, 8, 63, 17),
('Sunset in Oia', 'Is it worth the hype and the crowds?', 'questions', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11, 6, 53, 17),
('The Grand Bazaar in Istanbul', 'A maze of shops and treasures.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 13, 5, 61, 14),
('Turkish bath experience', 'A must-do for relaxation.', 'tips', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10, 4, 61, 14),
('The best of New York City', 'What are your top 5 recommendations for a first-timer?', 'questions', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 12, 8, 46, 3),
('A walk through Central Park in the fall', 'So beautiful and peaceful.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 6, 46, 3),
('The nightlife of London', 'From traditional pubs to trendy clubs.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 14, 5, 47, 9),
('Changing of the Guard at Buckingham Palace', 'A classic London experience.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15, 4, 47, 9),
('The Pyramids and Sphinx in Cairo', 'Absolutely mind-blowing.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 7, 63, 21),
('Felucca ride on the Nile at sunset', 'So peaceful and relaxing.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 53, 21),
('Moscow''s stunning metro stations', 'Art galleries underground.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 6, 52, 22),
('The Kremlin and Red Square', 'The heart of Russia.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 5, 52, 22),
('The colorful houses of La Boca, Buenos Aires', 'A vibrant and lively neighborhood.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 14, 5, 58, 23),
('Learning to tango in Buenos Aires', 'An unforgettable cultural experience.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12, 4, 58, 23),
('The historic trams of Lisbon', 'A charming way to see the city.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 13, 6, 57, 24),
('Feasting on pastéis de nata in Belém', 'I can''t stop eating them!', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 62, 24),
('The imperial palaces of Vienna', 'So much opulence and history.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 5, 64, 25),
('Attending a classical music concert in Vienna', 'A magical evening.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 4, 64, 25),
('Hiking to the top of Arthur''s Seat in Edinburgh', 'Panoramic views of the city.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 7, 59, 26),
('Exploring the historic Royal Mile', 'So much to see and do.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 59, 26),
('The ancient ruins of Teotihuacan, near Mexico City', 'Climbing the Pyramid of the Sun.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 14, 6, 63, 27),
('The food scene in Mexico City', 'Tacos, tortas, and tlayudas!', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 8, 62, 27),
('The chaotic charm of Hanoi''s Old Quarter', 'A sensory overload in the best way.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 6, 61, 28),
('Water puppet show in Hanoi', 'A unique and traditional art form.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13, 4, 61, 28),
('The ruin bars of Budapest', 'So quirky and cool.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 14, 7, 59, 29),
('A cruise on the Danube River at night', 'The Parliament building is stunning.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 5, 59, 29),
('The gateway to Machu Picchu: Cusco', 'Acclimatizing and exploring the city.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 16, 6, 59, 30),
('The San Pedro Market in Cusco', 'A feast for the senses.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14, 5, 59, 30),
('Island hopping in the Philippines', 'Crystal clear water and white sand beaches.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 20, 9, 53, 15),
('Scuba diving in the coral reefs', 'An underwater paradise.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18, 7, 53, 15),
('Trekking in the Himalayas, Nepal', 'A challenging but life-changing journey.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 19, 8, 59, 51),
('Exploring the temples of Kathmandu', 'A spiritual and cultural hub.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 6, 54, 51),
('On safari in Kruger National Park, South Africa', 'Searching for the Big Five.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 7, 61, 6),
('The Blyde River Canyon', 'One of the largest canyons on Earth.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 61, 6),
('The stunning landscapes of Iceland', 'Waterfalls, glaciers, and volcanoes.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 20, 9, 65, 44),
('Chasing waterfalls on the south coast of Iceland', 'So many beautiful stops.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18, 7, 65, 44),
('Road tripping through New Zealand''s South Island', 'The most beautiful country in the world?', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 19, 8, 63, 70),
('Adrenaline activities in Queenstown', 'Bungy jumping, skydiving, and more.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17, 6, 65, 70),
('The ancient city of Rome', 'So much to see, so little time!', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 15, 6, 63, 5),
('A food tour in Trastevere', 'The best way to experience Roman cuisine.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 8, 62, 5),
('The temples of Bagan, Myanmar', 'Sunrise from a hot air balloon.', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 7, 64, 55),
('Exploring the ancient city by e-bike', 'The best way to get around.', 'tips', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 64, 55),
('The mountains of Switzerland', 'Hiking in the Alps.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 17, 7, 49, 39),
('A scenic train ride through the Swiss Alps', 'The views are breathtaking.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 6, 52, 39),
('The beautiful beaches of Thailand', 'Island hopping in the Andaman Sea.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 8, 53, 8),
('Learning to cook Thai food in Chiang Mai', 'A delicious and fun experience.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 6, 52, 8),
('The wildlife of Costa Rica', 'Sloths, monkeys, and toucans!', 'experience', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 17, 7, 51, 15),
('Ziplining through the cloud forests', 'An exhilarating experience.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 6, 55, 15),
('The desert landscapes of Namibia', 'Dune 45 and Deadvlei.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 7, 60, 66),
('The Skeleton Coast', 'Eerie and beautiful.', 'post', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 5, 60, 66),
('The culture and traditions of Japan', 'A fascinating and beautiful country.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 17, 7, 4, 2),
('A stay in a traditional ryokan', 'An unforgettable cultural experience.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 6, 4, 2),
('The great outdoors of Canada', 'Lakes, mountains, and forests.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 8, 59, 61),
('Canoeing on a pristine Canadian lake', 'So peaceful and beautiful.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 6, 59, 61),
('The history and charm of the American South', 'New Orleans, Charleston, and Savannah.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 17, 7, 53, 3),
('The music and food of New Orleans', 'Jazz, blues, and Creole cuisine.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 6, 52, 3),
('The natural wonders of Australia', 'The Outback, the Great Barrier Reef, and more.', 'post', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP, 18, 8, 60, 4),
('Snorkeling in the Great Barrier Reef', 'An incredible underwater world.', 'experience', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16, 6, 63, 4);

-- Insert image URLs into post_images table
INSERT INTO post_images (post_id, image_urls)
VALUES
(1, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/night+eifel+tower.jpeg'),
(2, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/sushi+in+tokyo.jpeg'),
(4, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/sydney+beaches.jpeg'),
(5, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/colloseum.jpeg'),
(6, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/mountain+hike.jpeg'),
(7, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/carnival+in+rio.jpeg'),
(8, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/bangkok+temple.jpeg'),
(9, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/london+eye+view.jpeg'),
(10, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/amsterdam+canal.jpeg'),
(11, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/paris+cafe.jpeg'),
(12, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/tokyo+night+life.jpeg'),
(14, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/sydney+opera+house.jpeg'),
(15, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/roman+forum.jpeg'),
(16, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/cape+town+sunset.jpeg'),
(17, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rio+beaches+1.jpeg'),
(17, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rio+beaches+2.jpeg'),
(18, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/bangkok+market+1.jpeg'),
(18, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/bangkok+market+2.jpeg'),
(20, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/amsterdam+bikes.jpeg'),
(21, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/dubai+desert+safari.jpeg'),
(22, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/kyoto+temples+1.jpeg'),
(22, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/kyoto+temples+2.jpeg'),
(23, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/barcelona+gaudi.jpeg'),
(25, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/hawaii+surfing+1.jpeg'),
(25, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/hawaii+surfing+2.jpeg'),
(26, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/prague+castl.jpeg'),
(27, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/santorini+sunsets.jpeg'),
(28, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/seoul+street+food.jpeg'),
(30, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/marrakechriad.jpg'),
(31, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/paris+louvre.jpeg'),
(32, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/tokyo+onsen.jpeg'),
(33, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/nyc+skyline.jpeg'),
(34, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/sydney+harbour.jpeg'),
(35, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rome+pasta.jpeg'),
(36, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/cape+town+wineries.jpeg'),
(36, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/cape+town+wineries+2.jpeg'),
(37, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/rio+samba.jpeg'),
(38, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/bangkok+tuk+tuk.jpeg'),
(39, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/london+pubs.jpeg'),
(40, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/amsterdam+art.jpeg'),
(41, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/dubai+mall.jpeg'),
(42, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/kyoto+gardens.jpeg'),
(43, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/barcelona+beach.jpeg'),
(44, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/istanbul+mosque.jpeg'),
(45, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/hawaii+volcano.jpeg'),
(47, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/santorini+view.jpeg'),
(48, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/seoul+k+drama.jpeg'),
(49, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/vancouver+park.jpeg'),
(50, 'https://wanderverse-cloud-bucket.s3.ap-southeast-1.amazonaws.com/marakesh+riads.jpeg');
(81, 'https://images.unsplash.com/photo-1572252192994-f433a42d1848?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2Fpcm98ZW58MHx8MHx8fDA%3D'),
(82, 'https://images.unsplash.com/photo-1529973622019-a1b7df37a726?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bW9zY293fGVufDB8fDB8fHww'),
(83, 'https://images.unsplash.com/photo-1589908479323-210313783a9a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVlbm9zJTIwYWlyZXN8ZW58MHx8MHx8fDA%3D'),
(84, 'https://images.unsplash.com/photo-1586719593754-20d8579c1313?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGlzYm9ufGVufDB8fDB8fHww'),
(85, 'https://images.unsplash.com/photo-1599818459952-3269b2d39546?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmllbm5hfGVufDB8fDB8fHww'),
(86, 'https://images.unsplash.com/photo-1598434024113-d1cfd3c13d04?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8ZWRpbmJ1cmdofGVufDB8fDB8fHww'),
(87, 'https://images.unsplash.com/photo-1574482215228-2b1b3eae41e2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bWV4aWNvJTIwY2l0eXxlbnwwfHwwfHx8MA%3D%3D'),
(88, 'https://images.unsplash.com/photo-1593468595856-c3a8125a2e1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGFub2l8ZW58MHx8MHx8fDA%3D'),
(89, 'https://images.unsplash.com/photo-1593922822129-397c0a0c3b88?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YnVkYXBlc3R8ZW58MHx8MHx8fDA%3D'),
(90, 'https://images.unsplash.com/photo-1569420829023-96b636a8712e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y3VzY298ZW58MHx8MHx8fDA%3D');

-- Insert 20 Comments (10 top-level, 10 replies, across 10 posts)
INSERT INTO comments (content, post_id, user_id, parent_comment_id, created_at)
VALUES
('Wow, amazing view!', 1, 2, NULL, CURRENT_TIMESTAMP - INTERVAL '1 day'), -- Post 1, top-level
('Totally agree!', 1, 3, 1, CURRENT_TIMESTAMP - INTERVAL '12 hours'), -- Reply to comment 1
('Best sushi spot?', 2, 4, NULL, CURRENT_TIMESTAMP - INTERVAL '2 days'), -- Post 2, top-level
('Try Sushi Zanmai!', 2, 1, 3, CURRENT_TIMESTAMP - INTERVAL '1 day'), -- Reply to comment 3
('Use the MetroCard.', 3, 5, NULL, CURRENT_TIMESTAMP - INTERVAL '3 days'), -- Post 3, top-level
('Avoid rush hours!', 3, 2, 5, CURRENT_TIMESTAMP - INTERVAL '2 days'), -- Reply to comment 5
('Loved the Colosseum!', 5, 3, NULL, CURRENT_TIMESTAMP - INTERVAL '4 days'), -- Post 5, top-level
('Check the audio guide.', 5, 4, 7, CURRENT_TIMESTAMP - INTERVAL '3 days'), -- Reply to comment 7
('Carnival was wild!', 7, 1, NULL, CURRENT_TIMESTAMP - INTERVAL '5 days'), -- Post 7, top-level
('Which samba school?', 7, 5, 9, CURRENT_TIMESTAMP - INTERVAL '4 days'), -- Reply to comment 9
('Great cafes!', 11, 4, NULL, CURRENT_TIMESTAMP - INTERVAL '6 days'), -- Post 11, top-level
('Try Cafe de Flore.', 11, 2, 11, CURRENT_TIMESTAMP - INTERVAL '5 days'), -- Reply to comment 11
('Free museums?', 19, 3, NULL, CURRENT_TIMESTAMP - INTERVAL '7 days'), -- Post 19, top-level
('British Museum is free!', 19, 1, 13, CURRENT_TIMESTAMP - INTERVAL '6 days'), -- Reply to comment 13
('Sagrada was stunning!', 23, 5, NULL, CURRENT_TIMESTAMP - INTERVAL '8 days'), -- Post 23, top-level
('Book tickets early!', 23, 4, 15, CURRENT_TIMESTAMP - INTERVAL '7 days'), -- Reply to comment 15
('Oia is magical!', 27, 2, NULL, CURRENT_TIMESTAMP - INTERVAL '9 days'), -- Post 27, top-level
('Best sunset spot?', 27, 3, 17, CURRENT_TIMESTAMP - INTERVAL '8 days'), -- Reply to comment 17
('Louvre tips?', 31, 1, NULL, CURRENT_TIMESTAMP - INTERVAL '10 days'), -- Post 31, top-level
('Get the audio tour!', 31, 5, 19, CURRENT_TIMESTAMP - INTERVAL '9 days'); -- Reply to comment 19
('Incredible shot!', 81, 47, NULL, CURRENT_TIMESTAMP - INTERVAL '1 day'),
('Is it very cold there?', 82, 46, NULL, CURRENT_TIMESTAMP - INTERVAL '2 days'),
('Makes me want to dance!', 83, 49, NULL, CURRENT_TIMESTAMP - INTERVAL '12 hours'),
('Any tips for finding the best pastel de nata?', 84, 48, NULL, CURRENT_TIMESTAMP - INTERVAL '1 day'),
('What an amazing view!', 86, 50, NULL, CURRENT_TIMESTAMP),
('Did you go inside the museum?', 87, 47, NULL, CURRENT_TIMESTAMP - INTERVAL '3 days'),
('I''ve heard so much about this!', 88, 48, NULL, CURRENT_TIMESTAMP - INTERVAL '2 days'),
('How was the water temperature?', 89, 49, NULL, CURRENT_TIMESTAMP - INTERVAL '1 day'),
('Definitely worth the climb!', 86, 46, 5, CURRENT_TIMESTAMP - INTERVAL '6 hours');

-- Insert 100 Likes (distributed across 50 posts, 5 users)
INSERT INTO likes (post_id, user_id, created_at)
VALUES
(1, 2, CURRENT_TIMESTAMP - INTERVAL '1 day'), (1, 3, CURRENT_TIMESTAMP - INTERVAL '12 hours'),
(2, 4, CURRENT_TIMESTAMP - INTERVAL '2 days'), (2, 1, CURRENT_TIMESTAMP - INTERVAL '1 day'), (2, 5, CURRENT_TIMESTAMP - INTERVAL '18 hours'),
(3, 2, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(4, 3, CURRENT_TIMESTAMP - INTERVAL '4 days'), (4, 4, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(5, 1, CURRENT_TIMESTAMP - INTERVAL '5 days'), (5, 5, CURRENT_TIMESTAMP - INTERVAL '4 days'), (5, 2, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(6, 3, CURRENT_TIMESTAMP - INTERVAL '6 days'), (6, 4, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(7, 5, CURRENT_TIMESTAMP - INTERVAL '7 days'),
(8, 1, CURRENT_TIMESTAMP - INTERVAL '8 days'), (8, 2, CURRENT_TIMESTAMP - INTERVAL '7 days'),
(9, 3, CURRENT_TIMESTAMP - INTERVAL '9 days'), (9, 4, CURRENT_TIMESTAMP - INTERVAL '8 days'), (9, 5, CURRENT_TIMESTAMP - INTERVAL '7 days'),
(10, 2, CURRENT_TIMESTAMP - INTERVAL '10 days'), (10, 1, CURRENT_TIMESTAMP - INTERVAL '9 days'),
(11, 4, CURRENT_TIMESTAMP - INTERVAL '11 days'),
(12, 5, CURRENT_TIMESTAMP - INTERVAL '12 days'), (12, 3, CURRENT_TIMESTAMP - INTERVAL '11 days'), (12, 2, CURRENT_TIMESTAMP - INTERVAL '10 days'),
(13, 1, CURRENT_TIMESTAMP - INTERVAL '13 days'), (13, 4, CURRENT_TIMESTAMP - INTERVAL '12 days'),
(14, 2, CURRENT_TIMESTAMP - INTERVAL '14 days'),
(15, 3, CURRENT_TIMESTAMP - INTERVAL '15 days'), (15, 5, CURRENT_TIMESTAMP - INTERVAL '14 days'),
(16, 4, CURRENT_TIMESTAMP - INTERVAL '16 days'), (16, 1, CURRENT_TIMESTAMP - INTERVAL '15 days'), (16, 2, CURRENT_TIMESTAMP - INTERVAL '14 days'),
(17, 5, CURRENT_TIMESTAMP - INTERVAL '17 days'), (17, 3, CURRENT_TIMESTAMP - INTERVAL '16 days'),
(18, 2, CURRENT_TIMESTAMP - INTERVAL '18 days'),
(19, 1, CURRENT_TIMESTAMP - INTERVAL '19 days'), (19, 4, CURRENT_TIMESTAMP - INTERVAL '18 days'),
(20, 5, CURRENT_TIMESTAMP - INTERVAL '20 days'), (20, 3, CURRENT_TIMESTAMP - INTERVAL '19 days'), (20, 2, CURRENT_TIMESTAMP - INTERVAL '18 days'),
(21, 1, CURRENT_TIMESTAMP - INTERVAL '1 day'), (21, 4, CURRENT_TIMESTAMP - INTERVAL '12 hours'),
(22, 2, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(23, 3, CURRENT_TIMESTAMP - INTERVAL '3 days'), (23, 5, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(24, 4, CURRENT_TIMESTAMP - INTERVAL '4 days'), (24, 1, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(25, 2, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(26, 3, CURRENT_TIMESTAMP - INTERVAL '6 days'), (26, 5, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(27, 4, CURRENT_TIMESTAMP - INTERVAL '7 days'), (27, 1, CURRENT_TIMESTAMP - INTERVAL '6 days'), (27, 2, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(28, 3, CURRENT_TIMESTAMP - INTERVAL '8 days'), (28, 5, CURRENT_TIMESTAMP - INTERVAL '7 days'),
(29, 4, CURRENT_TIMESTAMP - INTERVAL '9 days'),
(30, 1, CURRENT_TIMESTAMP - INTERVAL '10 days'), (30, 2, CURRENT_TIMESTAMP - INTERVAL '9 days'),
(31, 3, CURRENT_TIMESTAMP - INTERVAL '11 days'), (31, 5, CURRENT_TIMESTAMP - INTERVAL '10 days'), (31, 4, CURRENT_TIMESTAMP - INTERVAL '9 days'),
(32, 2, CURRENT_TIMESTAMP - INTERVAL '12 days'), (32, 1, CURRENT_TIMESTAMP - INTERVAL '11 days'),
(33, 3, CURRENT_TIMESTAMP - INTERVAL '13 days'),
(34, 4, CURRENT_TIMESTAMP - INTERVAL '14 days'), (34, 5, CURRENT_TIMESTAMP - INTERVAL '13 days'),
(35, 1, CURRENT_TIMESTAMP - INTERVAL '15 days'), (35, 2, CURRENT_TIMESTAMP - INTERVAL '14 days'), (35, 3, CURRENT_TIMESTAMP - INTERVAL '13 days'),
(36, 4, CURRENT_TIMESTAMP - INTERVAL '16 days'), (36, 5, CURRENT_TIMESTAMP - INTERVAL '15 days'),
(37, 1, CURRENT_TIMESTAMP - INTERVAL '17 days'),
(38, 2, CURRENT_TIMESTAMP - INTERVAL '18 days'), (38, 3, CURRENT_TIMESTAMP - INTERVAL '17 days'),
(39, 4, CURRENT_TIMESTAMP - INTERVAL '19 days'), (39, 5, CURRENT_TIMESTAMP - INTERVAL '18 days'), (39, 1, CURRENT_TIMESTAMP - INTERVAL '17 days'),
(40, 2, CURRENT_TIMESTAMP - INTERVAL '20 days'), (40, 3, CURRENT_TIMESTAMP - INTERVAL '19 days'),
(41, 4, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(42, 5, CURRENT_TIMESTAMP - INTERVAL '2 days'), (42, 1, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(43, 2, CURRENT_TIMESTAMP - INTERVAL '3 days'), (43, 3, CURRENT_TIMESTAMP - INTERVAL '2 days'), (43, 4, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(44, 5, CURRENT_TIMESTAMP - INTERVAL '4 days'), (44, 1, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(45, 2, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(46, 3, CURRENT_TIMESTAMP - INTERVAL '6 days'), (46, 4, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(47, 5, CURRENT_TIMESTAMP - INTERVAL '7 days'), (47, 1, CURRENT_TIMESTAMP - INTERVAL '6 days'), (47, 2, CURRENT_TIMESTAMP - INTERVAL '5 days'),
(48, 3, CURRENT_TIMESTAMP - INTERVAL '8 days'), (48, 4, CURRENT_TIMESTAMP - INTERVAL '7 days'),
(49, 5, CURRENT_TIMESTAMP - INTERVAL '9 days'),
(50, 1, CURRENT_TIMESTAMP - INTERVAL '10 days'), (50, 2, CURRENT_TIMESTAMP - INTERVAL '9 days');
(81, 2, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(81, 48, CURRENT_TIMESTAMP - INTERVAL '10 hours'),
(82, 49, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(83, 46, CURRENT_TIMESTAMP - INTERVAL '11 hours'),
(83, 47, CURRENT_TIMESTAMP - INTERVAL '10 hours'),
(83, 50, CURRENT_TIMESTAMP - INTERVAL '9 hours'),
(84, 1, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(84, 5, CURRENT_TIMESTAMP - INTERVAL '22 hours'),
(85, 3, CURRENT_TIMESTAMP),
(86, 2, CURRENT_TIMESTAMP - INTERVAL '5 hours'),
(86, 4, CURRENT_TIMESTAMP - INTERVAL '4 hours'),
(86, 48, CURRENT_TIMESTAMP - INTERVAL '3 hours'),
(86, 49, CURRENT_TIMESTAMP - INTERVAL '2 hours'),
(87, 1, CURRENT_TIMESTAMP - INTERVAL '3 days'),
(87, 50, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(88, 4, CURRENT_TIMESTAMP - INTERVAL '2 days'),
(88, 46, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(88, 47, CURRENT_TIMESTAMP - INTERVAL '12 hours'),
(89, 2, CURRENT_TIMESTAMP - INTERVAL '1 day'),
(89, 48, CURRENT_TIMESTAMP - INTERVAL '20 hours')