name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USERNAME }}
      run: |
        echo "$PRIVATE_KEY" > private.key
        chmod 600 private.key
        scp -o StrictHostKeyChecking=no -i private.key target/wanderverse_server-0.0.1-SNAPSHOT.jar $USER@$HOSTNAME:/home/deploy/wanderverse-service/wanderverse_server-0.0.1-SNAPSHOT.jar
        ssh -o StrictHostKeyChecking=no -i private.key $USER@$HOSTNAME "sudo chown deploy:deploy /home/deploy/wanderverse-service/application-prod.properties && sudo chmod 644 /home/deploy/wanderverse-service/application-prod.properties"
        ssh -o StrictHostKeyChecking=no -i private.key $USER@$HOSTNAME "sudo systemctl restart wanderverse.service"
        rm -f private.key
